#! /bin/sh

# nagios script to determine the state of a dirxml driver
# copyright (c) Lothar Haeger (lothar.haeger@steria-mummert.de)
# v1.1, 2007-05-21

PROGNAME=`/bin/basename $0`
PROGPATH=`echo $0 | /bin/sed -e 's,[\\/][^\\/][^\\/]*$,,'`

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

#DXCMD="/usr/bin/dxcmd"
DXCMD="dxcmd"
DXERR="/tmp/dxcmd_error"

print_help() {
    echo "Novell DirXML 1.1 and Identity Manager 2.x/3.x driver state detector plugin for Nagios"
    echo "Usage: $PROGNAME [-s hostname|ip-address] -u username, -p password -d driver-dn"
    echo "Usage: $PROGNAME [-h | --help]"
}

if [ $# -lt 1 ]; then
    print_help
    exit $STATE_UNKNOWN
fi

while test -n "$1"; do
    case "$1" in
        --help)
            print_help
            exit $STATE_OK
            ;;
        -h)
            print_help
            exit $STATE_OK
            ;;
        -u)
            username=$2
	    #echo $username
            shift
            ;;
        -p)
            password=$2
	    #echo $password
            shift
            ;;
        -s)
            server=$2
	    #echo $server
            shift
            ;;
        -d)
            driverdn=$2
	    #echo $driverdn
            shift
            ;;
        *)
            echo "Unknown argument: $1"
            print_help
            exit $STATE_UNKNOWN
            ;;
    esac
    shift
done

if [ "$server" == "" ]; then
#   dxcmd_output=`$DXCMD -user $username -password $password -getstate $driverdn 2>&1`
   dxcmd_output=`$DXCMD -user $username -password $password -getstate $driverdn 2>$DXERR`
else
#   dxcmd_output=`$DXCMD -host $server -user $username -password $password -getstate $driverdn 2>&1`
   dxcmd_output=`$DXCMD -host $server -user $username -password $password -getstate $driverdn 2>$DXERR`
fi

dxml_drvstate=$?
#echo "$dxcmd_output"
#echo "Driver State: $dxml_drvstate"

case $dxml_drvstate in
    0)	#stopped
	echo "Driver $driverdn is STOPPED."
        exit $STATE_CRITICAL
        ;;
    1) 	#starting
	echo "Driver $driverdn is STARTING..."
        exit $STATE_OK
        ;;
    2)	#running
	echo "Driver $driverdn is RUNNING."
        exit $STATE_OK
        ;;
    3)	#stopping
	echo "Driver $driverdn is STOPPING..."
        exit $STATE_WARNING
        ;;
   11)	#getting schema
	echo "Driver $driverdn is GETTING the application SCHEMA..."
        exit $STATE_OK
        ;;
   96)	#access forbidden
	echo "Driver $driverdn could not be checked because $username is NOT AUTHORIZED to do so. "
        exit $STATE_CRITICAL
        ;;
  167)	#does not exist
	echo "Driver $driverdn DOES NOT EXIST."
        exit $STATE_CRITICAL
        ;;
  255)	#generic error
	echo "Driver $driverdn could not be ckecked due to an UNKNOWN ERROR (`egrep 'xception' $DXERR`)."
        exit $STATE_CRITICAL
        ;;
    *)	#other dxcmd error
	echo "Driver $driverdn could not be ckecked due to an UNKNOWN ERROR (Error code $dxml_drvstate)"
        exit $STATE_CRITICAL
        ;;
esac

exit $STATE_CRITICAL
